meta_product_name: "Sustainably"
meta_title: "Sustainably - All you need to live a more sustainable life"
meta_description: "Find the sustainable options you were looking for. We got you covered with sustainable food, travel and fashion options as well as many other sustainable products and services you haven't even thought about."
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards